RASIS = [
    "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
    "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"
]

SUPPORTED_RASI_LANGS = {"hi", "ta", "kn", "te"}
DEFAULT_LANG = "en"

RASI_NAMES = {
    "en": {
        "Aries": "Aries",
        "Taurus": "Taurus",
        "Gemini": "Gemini",
        "Cancer": "Cancer",
        "Leo": "Leo",
        "Virgo": "Virgo",
        "Libra": "Libra",
        "Scorpio": "Scorpio",
        "Sagittarius": "Sagittarius",
        "Capricorn": "Capricorn",
        "Aquarius": "Aquarius",
        "Pisces": "Pisces",
    },
    "hi": {
        "Aries": "मेष",
        "Taurus": "वृषभ",
        "Gemini": "मिथुन",
        "Cancer": "कर्क",
        "Leo": "सिंह",
        "Virgo": "कन्या",
        "Libra": "तुला",
        "Scorpio": "वृश्चिक",
        "Sagittarius": "धनु",
        "Capricorn": "मकर",
        "Aquarius": "कुंभ",
        "Pisces": "मीन",
    },
    "ta": {
        "Aries": "மேஷம்",
        "Taurus": "ரிஷபம்",
        "Gemini": "மிதுனம்",
        "Cancer": "கடகம்",
        "Leo": "சிம்மம்",
        "Virgo": "கன்னி",
        "Libra": "துலாம்",
        "Scorpio": "விருச்சிகம்",
        "Sagittarius": "தனுசு",
        "Capricorn": "மகரம்",
        "Aquarius": "கும்பம்",
        "Pisces": "மீனம்",
    },
    "kn": {
        "Aries": "ಮೇಷ",
        "Taurus": "ವೃಷಭ",
        "Gemini": "ಮಿಥುನ",
        "Cancer": "ಕರ್ಕಟಕ",
        "Leo": "ಸಿಂಹ",
        "Virgo": "ಕನ್ಯಾ",
        "Libra": "ತುಲಾ",
        "Scorpio": "ವೃಶ್ಚಿಕ",
        "Sagittarius": "ಧನು",
        "Capricorn": "ಮಕರ",
        "Aquarius": "ಕುಂಭ",
        "Pisces": "ಮೀನ",
    },
    "te": {
        "Aries": "మేషం",
        "Taurus": "వృషభం",
        "Gemini": "మిథునం",
        "Cancer": "కర్కాటకం",
        "Leo": "సింహం",
        "Virgo": "కన్య",
        "Libra": "తుల",
        "Scorpio": "వృశ్చికం",
        "Sagittarius": "ధనుస్సు",
        "Capricorn": "మకరం",
        "Aquarius": "కుంభం",
        "Pisces": "మీనం",
    },
}
